### PR TITLE
 add config 'index_unique' for deal with 'UNIQUE index'

### PR DESCRIPTION
**Pull request by senique**
When MySQL table has a UNIQUE index, it comes an error lead to fail to create index for the remaining tables.

### CODE REVIEW

**Comment by kworr** [comment]
But we already do support UNIQUE indices. Can you check `tests/schema.sql` and verify that it can be converted correctly? Can you include a sample database schema that doesn't work for you?

**Comment by senique** [comment]
ERROR INFO: 
  psycopg2.ProgrammingError: UNIQUE index must contain all columns in the distribution key of relation "test_table"

MIGRATE TABLE SCHEMA: 
CREATE TABLE `test_db`.`Untitled`  (
  `id` int(11) NOT NULL COMMENT 'comment  id key',
  `code` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'comment code with UNIQUE index',
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'comment state',
  PRIMARY KEY (`id`) USING BTREE,
  **UNIQUE INDEX `test_unique_index`(`code`) USING BTREE**
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

**Comment by senique** [comment]
`UNIQUE INDEX test_unique_index(code) USING BTREE`
replace with below can work fine: 
`UNIQUE INDEX `test_unique_index`(`id`, `code`, `name`) USING BTREE`

**Comment by senique** [comment]
I've created an issue for this.

**Pull request closed without merging**
